<h2>Section: Strain your brain!</h2>

<h3>▶ Strings can be tricky sometimes *</h3>

<p>1.</p>

<pre><code>&gt;&gt;&gt; a = "some_string"
&gt;&gt;&gt; id(a)
140420665652016
&gt;&gt;&gt; id("some" + "_" + "string") # Notice that both the ids are same.
140420665652016
</code></pre>

<p>2.</p>

<pre><code>&gt;&gt;&gt; a = "wtf"
&gt;&gt;&gt; b = "wtf"
&gt;&gt;&gt; a is b
True

&gt;&gt;&gt; a = "wtf!"
&gt;&gt;&gt; b = "wtf!"
&gt;&gt;&gt; a is b
False

&gt;&gt;&gt; a, b = "wtf!", "wtf!"
&gt;&gt;&gt; a is b
True
</code></pre>

<p>3.</p>

<pre><code>&gt;&gt;&gt; 'a' * 20 is 'aaaaaaaaaaaaaaaaaaaa'
True
&gt;&gt;&gt; 'a' * 21 is 'aaaaaaaaaaaaaaaaaaaaa'
False
</code></pre>

<p>Makes sense, right?</p>

<h4>💡 Explanation:</h4>

<ul>
<li>Such behavior is due to CPython optimization (called string interning) that tries to use existing immutable objects in some cases rather than creating a new object every time.</li>
<li>After being interned, many variables may point to the same string object in memory (thereby saving memory).</li>
<li>In the snippets above, strings are implicitly interned. The decision of when to implicitly intern a string is implementation dependent. There are some facts that can be used to guess if a string will be interned or not:
<ul>
<li>All length 0 and length 1 strings are interned.</li>
<li>Strings are interned at compile time (<code>'wtf'</code> will be interned but <code>''.join(['w', 't', 'f']</code> will not be interned)</li>
<li>Strings that are not composed of ASCII letters, digits or underscores, are not interned. This explains why <code>'wtf!'</code> was not interned due to <code>!</code>. Cpython implementation of this rule can be found <a href="https://github.com/python/cpython/blob/3.6/Objects/codeobject.c#L19">here</a>
<img src="/images/string-intern/string_intern.png" alt=""></li>
</ul></li>
<li>When <code>a</code> and <code>b</code> are set to <code>"wtf!"</code> in the same line, the Python interpreter creates a new object, then references the second variable at the same time. If you do it on separate lines, it doesn't "know" that there's already <code>wtf!</code> as an object (because <code>"wtf!"</code> is not implicitly interned as per the facts mentioned above). It's a compiler optimization and specifically applies to the interactive environment.</li>
<li>Constant folding is a technique for <a href="https://en.wikipedia.org/wiki/Peephole_optimization">peephole optimization</a> in Python. This means the expression <code>'a'*20</code> is replaced by <code>'aaaaaaaaaaaaaaaaaaaa'</code> during compilation to reduce few clock cycles during runtime. Constant folding only occurs for strings having length less than 20. (Why? Imagine the size of <code>.pyc</code> file generated as a result of the expression <code>'a'*10**10</code>). <a href="https://github.com/python/cpython/blob/3.6/Python/peephole.c#L288">Here's</a> the implementation source for the same.</li>
</ul>

<hr />

<h3>▶ Time for some hash brownies!</h3>

<p>1.</p>

<pre><code>some_dict = {}
some_dict[5.5] = "Ruby"
some_dict[5.0] = "JavaScript"
some_dict[5] = "Python"
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; some_dict[5.5]
"Ruby"
&gt;&gt;&gt; some_dict[5.0]
"Python"
&gt;&gt;&gt; some_dict[5]
"Python"
</code></pre>

<p>"Python" destroyed the existence of "JavaScript"?</p>

<h4>💡 Explanation</h4>

<ul>
<li>Python dictionaries check for equality and compare the hash value to determine if two keys are the same.</li>
<li><p>Immutable objects with same value always have the same hash in Python.</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>5 == 5.0
        True
      hash(5) == hash(5.0)
        True</p>
    </blockquote>
  </blockquote>
</blockquote>

<p><strong>Note:</strong> Objects with different values may also have same hash (known as hash collision).</p></li>
<li>When the statement <code>some_dict[5] = "Python"</code> is executed, the existing value "JavaScript" is overwritten with "Python" because Python recognizes <code>5</code> and <code>5.0</code> as the same keys of the dictionary <code>some_dict</code>.</li>
<li>This StackOverflow <a href="https://stackoverflow.com/a/32211042/4354153">answer</a> explains beautifully the rationale behind it.</li>
</ul>

<hr />

<h3>▶ Return return everywhere!</h3>

<pre><code>def some_func():
    try:
        return 'from_try'
    finally:
        return 'from_finally'
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; some_func()
'from_finally'
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>When a <code>return</code>, <code>break</code> or <code>continue</code> statement is executed in the <code>try</code> suite of a "try…finally" statement, the <code>finally</code> clause is also executed ‘on the way out.</li>
<li>The return value of a function is determined by the last <code>return</code> statement executed. Since the <code>finally</code> clause always executes, a <code>return</code> statement executed in the <code>finally</code> clause will always be the last one executed.</li>
</ul>

<hr />

<h3>▶ Deep down, we're all the same. *</h3>

<pre><code>class WTF:
  pass
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; WTF() == WTF() # two different instances can't be equal
False
&gt;&gt;&gt; WTF() is WTF() # identities are also different
False
&gt;&gt;&gt; hash(WTF()) == hash(WTF()) # hashes _should_ be different as well
True
&gt;&gt;&gt; id(WTF()) == id(WTF())
True
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>When <code>id</code> was called, Python created a <code>WTF</code> class object and passed it to the <code>id</code> function. The <code>id</code> function takes its <code>id</code> (its memory location), and throws away the object. The object is destroyed.</li>
<li>When we do this twice in succession, Python allocates the same memory location to this second object as well. Since (in CPython) <code>id</code> uses the memory location as the object id, the id of the two objects is the same.</li>
<li>So, object's id is unique only for the lifetime of the object. After the object is destroyed, or before it is created, something else can have the same id.</li>
<li><p>But why did the <code>is</code> operator evaluated to <code>False</code>? Let's see with this snippet.</p>

<p>class WTF(object):
    def __init__(self): print("I ")
    def __del__(self): print("D ")</p>

<p><strong>Output:</strong></p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>WTF() is WTF()
        I I D D
      id(WTF()) == id(WTF())
        I D I D</p>
    </blockquote>
  </blockquote>
</blockquote>

<p>As you may observe, the order in which the objects are destroyed is what made all the difference here.</p></li>
</ul>

<hr />

<h3>▶ For what?</h3>

<pre><code>some_string = "wtf"
some_dict = {}
for i, some_dict[i] in enumerate(some_string):
    pass
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; some_dict # An indexed dict is created.
{0: 'w', 1: 't', 2: 'f'}
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li><p>A <code>for</code> statement is defined in the <a href="https://docs.python.org/3/reference/grammar.html">Python grammar</a> as:
<code>
for_stmt: 'for' exprlist 'in' testlist ':' suite ['else' ':' suite]
</code>
Where <code>exprlist</code> is the assignment target. This means that the equivalent of <code>{exprlist} = {next_value}</code> is <strong>executed for each item</strong> in the iterable.
An interesting example that illustrates this:</p>

<p>for i in range(4):
      print(i)
      i = 10</p>

<p><strong>Output:</strong>
<code>
0
1
2
3
</code></p>

<p>Did you expect the loop to run just once?</p>

<p><strong>💡 Explanation:</strong></p>

<ul>
<li>The assignment statement <code>i = 10</code> never affects the iterations of the loop because of the way for loops work in Python. Before the beginning of every iteration, the next item provided by the iterator (<code>range(4)</code> this case) is unpacked and assigned the target list variables (<code>i</code> in this case).</li>
</ul></li>
<li><p>The <code>enumerate(some_string)</code> function yields a new value <code>i</code> (A counter going up) and a character from the <code>some_string</code> in each iteration. It then sets the (just assigned) <code>i</code> key of the dictionary <code>some_dict</code> to that character. The unrolling of the loop can be simplified as:</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>i, some_dict[i] = (0, 'w')
      i, some_dict[i] = (1, 't')
      i, some_dict[i] = (2, 'f')
      some_dict</p>
    </blockquote>
  </blockquote>
</blockquote></li>
</ul>

<hr />

<h3>▶ Evaluation time discrepancy</h3>

<p>1.</p>

<pre><code>array = [1, 8, 15]
g = (x for x in array if array.count(x) &gt; 0)
array = [2, 8, 22]
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; print(list(g))
[8]
</code></pre>

<p>2.</p>

<pre><code>array_1 = [1,2,3,4]
g1 = (x for x in array_1)
array_1 = [1,2,3,4,5]

array_2 = [1,2,3,4]
g2 = (x for x in array_2)
array_2[:] = [1,2,3,4,5]
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; print(list(g1))
[1,2,3,4]

&gt;&gt;&gt; print(list(g2))
[1,2,3,4,5]
</code></pre>

<h4>💡 Explanation</h4>

<ul>
<li>In a <a href="https://wiki.python.org/moin/Generators">generator</a> expression, the <code>in</code> clause is evaluated at declaration time, but the conditional clause is evaluated at runtime.</li>
<li>So before runtime, <code>array</code> is re-assigned to the list <code>[2, 8, 22]</code>, and since out of <code>1</code>, <code>8</code> and <code>15</code>, only the count of <code>8</code> is greater than <code>0</code>, the generator only yields <code>8</code>.</li>
<li>The differences in the output of <code>g1</code> and <code>g2</code> in the second part is due the way variables <code>array_1</code> and <code>array_2</code> are re-assigned values.</li>
<li>In the first case, <code>array_1</code> is binded to the new object <code>[1,2,3,4,5]</code> and since the <code>in</code> clause is evaluated at the declaration time it still refers to the old object <code>[1,2,3,4]</code> (which is not destroyed).</li>
<li>In the second case, the slice assignment to <code>array_2</code> updates the same old object <code>[1,2,3,4]</code> to <code>[1,2,3,4,5]</code>. Hence both the <code>g2</code> and <code>array_2</code> still have reference to the same object (which has now been updated to <code>[1,2,3,4,5]</code>).</li>
</ul>

<hr />

<h3>▶ <code>is</code> is not what it is!</h3>

<p>The following is a very famous example present all over the internet.</p>

<pre><code>&gt;&gt;&gt; a = 256
&gt;&gt;&gt; b = 256
&gt;&gt;&gt; a is b
True

&gt;&gt;&gt; a = 257
&gt;&gt;&gt; b = 257
&gt;&gt;&gt; a is b
False

&gt;&gt;&gt; a = 257; b = 257
&gt;&gt;&gt; a is b
True
</code></pre>

<h4>💡 Explanation:</h4>

<p><strong>The difference between <code>is</code> and <code>==</code></strong></p>

<ul>
<li><code>is</code> operator checks if both the operands refer to the same object (i.e., it checks if the identity of the operands matches or not).</li>
<li><code>==</code> operator compares the values of both the operands and checks if they are the same.</li>
<li><p>So <code>is</code> is for reference equality and <code>==</code> is for value equality. An example to clear things up,</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>[] == []
        True
      [] is [] # These are two empty lists at two different memory locations.
        False</p>
    </blockquote>
  </blockquote>
</blockquote></li>
</ul>

<p><strong><code>256</code> is an existing object but <code>257</code> isn't</strong></p>

<p>When you start up python the numbers from <code>-5</code> to <code>256</code> will be allocated. These numbers are used a lot, so it makes sense just to have them ready.</p>

<p>Quoting from https://docs.python.org/3/c-api/long.html</p>

<blockquote>
  <p>The current implementation keeps an array of integer objects for all integers between -5 and 256, when you create an int in that range you just get back a reference to the existing object. So it should be possible to change the value of 1. I suspect the behavior of Python, in this case, is undefined. :-)</p>
</blockquote>

<pre><code>&gt;&gt;&gt; id(256)
10922528
&gt;&gt;&gt; a = 256
&gt;&gt;&gt; b = 256
&gt;&gt;&gt; id(a)
10922528
&gt;&gt;&gt; id(b)
10922528
&gt;&gt;&gt; id(257)
140084850247312
&gt;&gt;&gt; x = 257
&gt;&gt;&gt; y = 257
&gt;&gt;&gt; id(x)
140084850247440
&gt;&gt;&gt; id(y)
140084850247344
</code></pre>

<p>Here the interpreter isn't smart enough while executing <code>y = 257</code> to recognize that we've already created an integer of the value <code>257,</code> and so it goes on to create another object in the memory.</p>

<p><strong>Both <code>a</code> and <code>b</code> refer to the same object when initialized with same value in the same line.</strong></p>

<pre><code>&gt;&gt;&gt; a, b = 257, 257
&gt;&gt;&gt; id(a)
140640774013296
&gt;&gt;&gt; id(b)
140640774013296
&gt;&gt;&gt; a = 257
&gt;&gt;&gt; b = 257
&gt;&gt;&gt; id(a)
140640774013392
&gt;&gt;&gt; id(b)
140640774013488
</code></pre>

<ul>
<li>When a and b are set to <code>257</code> in the same line, the Python interpreter creates a new object, then references the second variable at the same time. If you do it on separate lines, it doesn't "know" that there's already <code>257</code> as an object.</li>
<li>It's a compiler optimization and specifically applies to the interactive environment. When you enter two lines in a live interpreter, they're compiled separately, therefore optimized separately. If you were to try this example in a <code>.py</code> file, you would not see the same behavior, because the file is compiled all at once.</li>
</ul>

<hr />

<h3>▶ A tic-tac-toe where X wins in the first attempt!</h3>

<pre><code># Let's initialize a row
row = [""]*3 #row i['', '', '']
# Let's make a board
board = [row]*3
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; board
[['', '', ''], ['', '', ''], ['', '', '']]
&gt;&gt;&gt; board[0]
['', '', '']
&gt;&gt;&gt; board[0][0]
''
&gt;&gt;&gt; board[0][0] = "X"
&gt;&gt;&gt; board
[['X', '', ''], ['X', '', ''], ['X', '', '']]
</code></pre>

<p>We didn't assign 3 "X"s or did we?</p>

<h4>💡 Explanation:</h4>

<p>When we initialize <code>row</code> variable, this visualization explains what happens in the memory</p>

<p><img src="/images/tic-tac-toe/after_row_initialized.png" alt="image" /></p>

<p>And when the <code>board</code> is initialized by multiplying the <code>row</code>, this is what happens inside the memory (each of the elements <code>board[0]</code>, <code>board[1]</code> and <code>board[2]</code> is a reference to the same list referred by <code>row</code>)</p>

<p><img src="/images/tic-tac-toe/after_board_initialized.png" alt="image" /></p>

<p>We can avoid this scenario here by not using <code>row</code> variable to generate <code>board</code>. (Asked in <a href="https://github.com/satwikkansal/wtfpython/issues/68">this</a> issue).</p>

<pre><code>&gt;&gt;&gt; board = [['']*3 for _ in range(3)]
&gt;&gt;&gt; board[0][0] = "X"
&gt;&gt;&gt; board
[['X', '', ''], ['', '', ''], ['', '', '']]
</code></pre>

<hr />

<h3>▶ The sticky output function</h3>

<pre><code>funcs = []
results = []
for x in range(7):
    def some_func():
        return x
    funcs.append(some_func)
    results.append(some_func())

funcs_results = [func() for func in funcs]
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; results
[0, 1, 2, 3, 4, 5, 6]
&gt;&gt;&gt; funcs_results
[6, 6, 6, 6, 6, 6, 6]
</code></pre>

<p>Even when the values of <code>x</code> were different in every iteration prior to appending <code>some_func</code> to <code>funcs</code>, all the functions return 6.</p>

<p>//OR</p>

<pre><code>&gt;&gt;&gt; powers_of_x = [lambda x: x**i for i in range(10)]
&gt;&gt;&gt; [f(2) for f in powers_of_x]
[512, 512, 512, 512, 512, 512, 512, 512, 512, 512]
</code></pre>

<h4>💡 Explanation</h4>

<ul>
<li><p>When defining a function inside a loop that uses the loop variable in its body, the loop function's closure is bound to the variable, not its value. So all of the functions use the latest value assigned to the variable for computation.</p></li>
<li><p>To get the desired behavior you can pass in the loop variable as a named variable to the function. <strong>Why this works?</strong> Because this will define the variable again within the function's scope.</p>

<pre><code>funcs = []
for x in range(7):
    def some_func(x=x):
        return x
    funcs.append(some_func)
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; funcs_results = [func() for func in funcs]
&gt;&gt;&gt; funcs_results
[0, 1, 2, 3, 4, 5, 6]
</code></pre></li>
</ul>

<hr />

<h3>▶ <code>is not ...</code> is not <code>is (not ...)</code></h3>

<pre><code>&gt;&gt;&gt; 'something' is not None
True
&gt;&gt;&gt; 'something' is (not None)
False
</code></pre>

<h4>💡 Explanation</h4>

<ul>
<li><code>is not</code> is a single binary operator, and has behavior different than using <code>is</code> and <code>not</code> separated.</li>
<li><code>is not</code> evaluates to <code>False</code> if the variables on either side of the operator point to the same object and <code>True</code> otherwise.</li>
</ul>

<hr />

<h3>▶ The surprising comma</h3>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; def f(x, y,):
...     print(x, y)
...
&gt;&gt;&gt; def g(x=4, y=5,):
...     print(x, y)
...
&gt;&gt;&gt; def h(x, **kwargs,):
  File "&lt;stdin&gt;", line 1
    def h(x, **kwargs,):
                     ^
SyntaxError: invalid syntax
&gt;&gt;&gt; def h(*args,):
  File "&lt;stdin&gt;", line 1
    def h(*args,):
                ^
SyntaxError: invalid syntax
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>Trailing comma is not always legal in formal parameters list of a Python function.</li>
<li>In Python, the argument list is defined partially with leading commas and partially with trailing commas. This conflict causes situations where a comma is trapped in the middle, and no rule accepts it.</li>
<li><strong>Note:</strong> The trailing comma problem is <a href="https://bugs.python.org/issue9232">fixed in Python 3.6</a>. The remarks in <a href="https://bugs.python.org/issue9232#msg248399">this</a> post discuss in brief different usages of trailing commas in Python.</li>
</ul>

<hr />

<h3>▶ Backslashes at the end of string</h3>

<p><strong>Output:</strong>
```</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>print("\ C:\")
      \ C:\
      print(r"\ C:")
      \ C:
      print(r"\ C:\")</p>
    </blockquote>
  </blockquote>
</blockquote>

<pre><code>File "&lt;stdin&gt;", line 1
  print(r"\ C:\")
                 ^
</code></pre>

<p>SyntaxError: EOL while scanning string literal
```</p>

<h4>💡 Explanation</h4>

<ul>
<li><p>In a raw string literal, as indicated by the prefix <code>r</code>, the backslash doesn't have the special meaning.</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>print(repr(r"wt\"f"))
        'wt\"f'</p>
    </blockquote>
  </blockquote>
</blockquote></li>
<li><p>What the interpreter actually does, though, is simply change the behavior of backslashes, so they pass themselves and the following character through. That's why backslashes don't work at the end of a raw string.</p></li>
</ul>

<hr />

<h3>▶ not knot!</h3>

<pre><code>x = True
y = False
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; not x == y
True
&gt;&gt;&gt; x == not y
  File "&lt;input&gt;", line 1
    x == not y
           ^
SyntaxError: invalid syntax
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>Operator precedence affects how an expression is evaluated, and <code>==</code> operator has higher precedence than <code>not</code> operator in Python.</li>
<li>So <code>not x == y</code> is equivalent to <code>not (x == y)</code> which is equivalent to <code>not (True == False)</code> finally evaluating to <code>True</code>.</li>
<li>But <code>x == not y</code> raises a <code>SyntaxError</code> because it can be thought of being equivalent to <code>(x == not) y</code> and not <code>x == (not y)</code> which you might have expected at first sight.</li>
<li>The parser expected the <code>not</code> token to be a part of the <code>not in</code> operator (because both <code>==</code> and <code>not in</code> operators have the same precedence), but after not being able to find an <code>in</code> token following the <code>not</code> token, it raises a <code>SyntaxError</code>.</li>
</ul>

<hr />

<h3>▶ Half triple-quoted strings</h3>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; print('wtfpython''')
wtfpython
&gt;&gt;&gt; print("wtfpython""")
wtfpython
&gt;&gt;&gt; # The following statements raise `SyntaxError`
&gt;&gt;&gt; # print('''wtfpython')
&gt;&gt;&gt; # print("""wtfpython")
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>Python supports implicit <a href="https://docs.python.org/2/reference/lexical_analysis.html#string-literal-concatenation">string literal concatenation</a>, Example,
<code>
&gt;&gt;&gt; print("wtf" "python")
wtfpython
&gt;&gt;&gt; print("wtf" "") # or "wtf"""
wtf
</code></li>
<li><code>'''</code> and <code>"""</code> are also string delimiters in Python which causes a SyntaxError because the Python interpreter was expecting a terminating triple quote as delimiter while scanning the currently encountered triple quoted string literal.</li>
</ul>

<hr />

<h3>▶ Midnight time doesn't exist?</h3>

<pre><code>from datetime import datetime

midnight = datetime(2018, 1, 1, 0, 0)
midnight_time = midnight.time()

noon = datetime(2018, 1, 1, 12, 0)
noon_time = noon.time()

if midnight_time:
    print("Time at midnight is", midnight_time)

if noon_time:
    print("Time at noon is", noon_time)
</code></pre>

<p><strong>Output:</strong>
<code>sh
('Time at noon is', datetime.time(12, 0))
</code>
The midnight time is not printed.</p>

<h4>💡 Explanation:</h4>

<p>Before Python 3.5, the boolean value for <code>datetime.time</code> object was considered to be <code>False</code> if it represented midnight in UTC. It is error-prone when using the <code>if obj:</code> syntax to check if the <code>obj</code> is null or some equivalent of "empty."</p>

<hr />

<h3>▶ What's wrong with booleans?</h3>

<p>1.</p>

<pre><code># A simple example to count the number of boolean and
# integers in an iterable of mixed data types.
mixed_list = [False, 1.0, "some_string", 3, True, [], False]
integers_found_so_far = 0
booleans_found_so_far = 0

for item in mixed_list:
    if isinstance(item, int):
        integers_found_so_far += 1
    elif isinstance(item, bool):
        booleans_found_so_far += 1
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; booleans_found_so_far
0
&gt;&gt;&gt; integers_found_so_far
4
</code></pre>

<p>2.</p>

<pre><code>another_dict = {}
another_dict[True] = "JavaScript"
another_dict[1] = "Ruby"
another_dict[1.0] = "Python"
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; another_dict[True]
"Python"
</code></pre>

<p>3.</p>

<pre><code>&gt;&gt;&gt; some_bool = True
&gt;&gt;&gt; "wtf"*some_bool
'wtf'
&gt;&gt;&gt; some_bool = False
&gt;&gt;&gt; "wtf"*some_bool
''
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li><p>Booleans are a subclass of <code>int</code></p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>isinstance(True, int)
        True
      isinstance(False, int)
        True</p>
    </blockquote>
  </blockquote>
</blockquote></li>
<li><p>The integer value of <code>True</code> is <code>1</code> and that of <code>False</code> is <code>0</code>.</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>True == 1 == 1.0 and False == 0 == 0.0
        True</p>
    </blockquote>
  </blockquote>
</blockquote></li>
<li><p>See this StackOverflow <a href="https://stackoverflow.com/a/8169049/4354153">answer</a> for the rationale behind it.</p></li>
</ul>

<hr />

<h3>▶ Class attributes and instance attributes</h3>

<p>1.</p>

<pre><code>class A:
    x = 1

class B(A):
    pass

class C(A):
    pass
</code></pre>

<p><strong>Ouptut:</strong></p>

<pre><code>&gt;&gt;&gt; A.x, B.x, C.x
(1, 1, 1)
&gt;&gt;&gt; B.x = 2
&gt;&gt;&gt; A.x, B.x, C.x
(1, 2, 1)
&gt;&gt;&gt; A.x = 3
&gt;&gt;&gt; A.x, B.x, C.x
(3, 2, 3)
&gt;&gt;&gt; a = A()
&gt;&gt;&gt; a.x, A.x
(3, 3)
&gt;&gt;&gt; a.x += 1
&gt;&gt;&gt; a.x, A.x
(4, 3)
</code></pre>

<p>2.</p>

<pre><code>class SomeClass:
    some_var = 15
    some_list = [5]
    another_list = [5]
    def __init__(self, x):
        self.some_var = x + 1
        self.some_list = self.some_list + [x]
        self.another_list += [x]
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; some_obj = SomeClass(420)
&gt;&gt;&gt; some_obj.some_list
[5, 420]
&gt;&gt;&gt; some_obj.another_list
[5, 420]
&gt;&gt;&gt; another_obj = SomeClass(111)
&gt;&gt;&gt; another_obj.some_list
[5, 111]
&gt;&gt;&gt; another_obj.another_list
[5, 420, 111]
&gt;&gt;&gt; another_obj.another_list is SomeClass.another_list
True
&gt;&gt;&gt; another_obj.another_list is some_obj.another_list
True
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>Class variables and variables in class instances are internally handled as dictionaries of a class object. If a variable name is not found in the dictionary of the current class, the parent classes are searched for it.</li>
<li>The <code>+=</code> operator modifies the mutable object in-place without creating a new object. So changing the attribute of one instance affects the other instances and the class attribute as well.</li>
</ul>

<hr />

<h3>▶ yielding None</h3>

<pre><code>some_iterable = ('a', 'b')

def some_func(val):
    return "something"
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; [x for x in some_iterable]
['a', 'b']
&gt;&gt;&gt; [(yield x) for x in some_iterable]
&lt;generator object &lt;listcomp&gt; at 0x7f70b0a4ad58&gt;
&gt;&gt;&gt; list([(yield x) for x in some_iterable])
['a', 'b']
&gt;&gt;&gt; list((yield x) for x in some_iterable)
['a', None, 'b', None]
&gt;&gt;&gt; list(some_func((yield x)) for x in some_iterable)
['a', 'something', 'b', 'something']
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>Source and explanation can be found here: https://stackoverflow.com/questions/32139885/yield-in-list-comprehensions-and-generator-expressions</li>
<li>Related bug report: http://bugs.python.org/issue10544</li>
</ul>

<hr />

<h3>▶ Mutating the immutable!</h3>

<pre><code>some_tuple = ("A", "tuple", "with", "values")
another_tuple = ([1, 2], [3, 4], [5, 6])
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; some_tuple[2] = "change this"
TypeError: 'tuple' object does not support item assignment
&gt;&gt;&gt; another_tuple[2].append(1000) #This throws no error
&gt;&gt;&gt; another_tuple
([1, 2], [3, 4], [5, 6, 1000])
&gt;&gt;&gt; another_tuple[2] += [99, 999]
TypeError: 'tuple' object does not support item assignment
&gt;&gt;&gt; another_tuple
([1, 2], [3, 4], [5, 6, 1000, 99, 999])
</code></pre>

<p>But I thought tuples were immutable...</p>

<h4>💡 Explanation:</h4>

<ul>
<li><p>Quoting from https://docs.python.org/2/reference/datamodel.html</p>

<blockquote>
  <p>Immutable sequences
      An object of an immutable sequence type cannot change once it is created. (If the object contains references to other objects, these other objects may be mutable and may be modified; however, the collection of objects directly referenced by an immutable object cannot change.)</p>
</blockquote></li>
<li><p><code>+=</code> operator changes the list in-place. The item assignment doesn't work, but when the exception occurs, the item has already been changed in place.</p></li>
</ul>

<hr />

<h3>▶ The disappearing variable from outer scope</h3>

<pre><code>e = 7
try:
    raise Exception()
except Exception as e:
    pass
</code></pre>

<p><strong>Output (Python 2.x):</strong></p>

<pre><code>&gt;&gt;&gt; print(e)
# prints nothing
</code></pre>

<p><strong>Output (Python 3.x):</strong></p>

<pre><code>&gt;&gt;&gt; print(e)
NameError: name 'e' is not defined
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li><p>Source: https://docs.python.org/3/reference/compound_stmts.html#except</p>

<p>When an exception has been assigned using <code>as</code> target, it is cleared at the end of the except clause. This is as if</p>

<p>except E as N:
      foo</p>

<p>was translated into</p>

<p>except E as N:
      try:
          foo
      finally:
          del N</p>

<p>This means the exception must be assigned to a different name to be able to refer to it after the except clause. Exceptions are cleared because, with the traceback attached to them, they form a reference cycle with the stack frame, keeping all locals in that frame alive until the next garbage collection occurs.</p></li>
<li><p>The clauses are not scoped in Python. Everything in the example is present in the same scope, and the variable <code>e</code> got removed due to the execution of the <code>except</code> clause. The same is not the case with functions which have their separate inner-scopes. The example below illustrates this:</p>

<pre><code> def f(x):
     del(x)
     print(x)

 x = 5
 y = [5, 4, 3]
</code></pre>

<p><strong>Output:</strong></p>

<pre><code> &gt;&gt;&gt;f(x)
 UnboundLocalError: local variable 'x' referenced before assignment
 &gt;&gt;&gt;f(y)
 UnboundLocalError: local variable 'x' referenced before assignment
 &gt;&gt;&gt; x
 5
 &gt;&gt;&gt; y
 [5, 4, 3]
</code></pre></li>
<li><p>In Python 2.x the variable name <code>e</code> gets assigned to <code>Exception()</code> instance, so when you try to print, it prints nothing.</p>

<p><strong>Output (Python 2.x):</strong></p>

<pre><code>&gt;&gt;&gt; e
Exception()
&gt;&gt;&gt; print e
# Nothing is printed!
</code></pre></li>
</ul>

<hr />

<h3>▶ When True is actually False</h3>

<pre><code>True = False
if True == False:
    print("I've lost faith in truth!")
</code></pre>

<p><strong>Output:</strong>
<code>
I've lost faith in truth!
</code></p>

<h4>💡 Explanation:</h4>

<ul>
<li>Initially, Python used to have no <code>bool</code> type (people used 0 for false and non-zero value like 1 for true). Then they added <code>True</code>, <code>False</code>, and a <code>bool</code> type, but, for backward compatibility, they couldn't make <code>True</code> and <code>False</code> constants- they just were built-in variables.</li>
<li>Python 3 was backward-incompatible, so it was now finally possible to fix that, and so this example won't work with Python 3.x!</li>
</ul>

<hr />

<h3>▶ From filled to None in one instruction...</h3>

<pre><code>some_list = [1, 2, 3]
some_dict = {
  "key_1": 1,
  "key_2": 2,
  "key_3": 3
}

some_list = some_list.append(4)
some_dict = some_dict.update({"key_4": 4})
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; print(some_list)
None
&gt;&gt;&gt; print(some_dict)
None
</code></pre>

<h4>💡 Explanation</h4>

<p>Most methods that modify the items of sequence/mapping objects like <code>list.append</code>, <code>dict.update</code>, <code>list.sort</code>, etc. modify the objects in-place and return <code>None</code>. The rationale behind this is to improve performance by avoiding making a copy of the object if the operation can be done in-place (Referred from <a href="http://docs.python.org/2/faq/design.html#why-doesn-t-list-sort-return-the-sorted-list">here</a>)</p>

<hr />

<h3>▶ Subclass relationships *</h3>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; from collections import Hashable
&gt;&gt;&gt; issubclass(list, object)
True
&gt;&gt;&gt; issubclass(object, Hashable)
True
&gt;&gt;&gt; issubclass(list, Hashable)
False
</code></pre>

<p>The Subclass relationships were expected to be transitive, right? (i.e., if <code>A</code> is a subclass of <code>B</code>, and <code>B</code> is a subclass of <code>C</code>, the <code>A</code> _should_ a subclass of <code>C</code>)</p>

<h4>💡 Explanation:</h4>

<ul>
<li>Subclass relationships are not necessarily transitive in Python. Anyone is allowed to define their own, arbitrary <code>__subclasscheck__</code> in a metaclass.</li>
<li>When <code>issubclass(cls, Hashable)</code> is called, it simply looks for non-Falsey "<code>__hash__</code>" method in <code>cls</code> or anything it inherits from.</li>
<li>Since <code>object</code> is hashable, but <code>list</code> is non-hashable, it breaks the transitivity relation.</li>
<li>More detailed explanation can be found <a href="https://www.naftaliharris.com/blog/python-subclass-intransitivity/">here</a>.</li>
</ul>

<hr />

<h3>▶ The mysterious key type conversion *</h3>

<pre><code>class SomeClass(str):
    pass

some_dict = {'s':42}
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; type(list(some_dict.keys())[0])
str
&gt;&gt;&gt; s = SomeClass('s')
&gt;&gt;&gt; some_dict[s] = 40
&gt;&gt;&gt; some_dict # expected: Two different keys-value pairs
{'s': 40}
&gt;&gt;&gt; type(list(some_dict.keys())[0])
str
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>Both the object <code>s</code> and the string <code>"s"</code> hash to the same value because <code>SomeClass</code> inherits the <code>__hash__</code> method of <code>str</code> class.</li>
<li><code>SomeClass("s") == "s"</code> evaluates to <code>True</code> because <code>SomeClass</code> also inherits <code>__eq__</code> method from <code>str</code> class.</li>
<li>Since both the objects hash to the same value and are equal, they are represented by the same key in the dictionary.</li>
<li><p>For the desired behavior, we can redefine the <code>__eq__</code> method in <code>SomeClass</code></p>

<p>class SomeClass(str):
    def __eq__(self, other):
        return (
            type(self) is SomeClass
            and type(other) is SomeClass
            and super().__eq__(other)
        )</p>

<pre><code># When we define a custom __eq__, Python stops automatically inheriting the
# __hash__ method, so we need to define it as well
__hash__ = str.__hash__
</code></pre>

<p>some_dict = {'s':42}</p>

<p><strong>Output:</strong></p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>s = SomeClass('s')
      some_dict[s] = 40
      some_dict
        {'s': 40, 's': 42}
      keys = list(some_dict.keys())
      type(keys[0]), type(keys[1])
        (__main__.SomeClass, str)</p>
    </blockquote>
  </blockquote>
</blockquote></li>
</ul>

<hr />

<h3>▶ Let's see if you can guess this?</h3>

<pre><code>a, b = a[b] = {}, 5
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; a
{5: ({...}, 5)}
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li><p>According to <a href="https://docs.python.org/2/reference/simple_stmts.html#assignment-statements">Python language reference</a>, assignment statements have the form
<code>
(target_list "=")+ (expression_list | yield_expression)
</code>
and</p>

<blockquote>
  <p>An assignment statement evaluates the expression list (remember that this can be a single expression or a comma-separated list, the latter yielding a tuple) and assigns the single resulting object to each of the target lists, from left to right.</p>
</blockquote></li>
<li><p>The <code>+</code> in <code>(target_list "=")+</code> means there can be <strong>one or more</strong> target lists. In this case, target lists are <code>a, b</code> and <code>a[b]</code> (note the expression list is exactly one, which in our case is <code>{}, 5</code>).</p></li>
<li><p>After the expression list is evaluated, it's value is unpacked to the target lists from <strong>left to right</strong>. So, in our case, first the <code>{}, 5</code> tuple is unpacked to <code>a, b</code> and we now have <code>a = {}</code> and <code>b = 5</code>.</p></li>
<li><p><code>a</code> is now assigned to <code>{}</code> which is a mutable object.</p></li>
<li><p>The second target list is <code>a[b]</code> (you may expect this to throw an error because both <code>a</code> and <code>b</code> have not been defined in the statements before. But remember, we just assigned <code>a</code> to <code>{}</code> and <code>b</code> to <code>5</code>).</p></li>
<li><p>Now, we are setting the key <code>5</code> in the dictionary to the tuple <code>({}, 5)</code> creating a circular reference (the <code>{...}</code> in the output refers to the same object that <code>a</code> is already referencing). Another simpler example of circular reference could be</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>some_list = some_list[0] = [0]
      some_list
        [[...]]
      some_list[0]
        [[...]]
      some_list is some_list[0]
        True
      some_list[0][0][0][0][0][0] == some_list
        True</p>
    </blockquote>
  </blockquote>
</blockquote>

<p>Similar is the case in our example (<code>a[b][0]</code> is the same object as <code>a</code>)</p></li>
<li><p>So to sum it up, you can break the example down to</p>

<p>a, b = {}, 5
  a[b] = a, b</p>

<p>And the circular reference can be justified by the fact that <code>a[b][0]</code> is the same object as <code>a</code></p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>a[b][0] is a
        True</p>
    </blockquote>
  </blockquote>
</blockquote></li>
</ul>

<hr />

<hr />

<h2>Section: Appearances are deceptive!</h2>

<h3>▶ Skipping lines?</h3>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; value = 11
&gt;&gt;&gt; valuе = 32
&gt;&gt;&gt; value
11
</code></pre>

<p>Wut?</p>

<p><strong>Note:</strong> The easiest way to reproduce this is to simply copy the statements from the above snippet and paste them into your file/shell.</p>

<h4>💡 Explanation</h4>

<p>Some non-Western characters look identical to letters in the English alphabet but are considered distinct by the interpreter.</p>

<pre><code>&gt;&gt;&gt; ord('е') # cyrillic 'e' (Ye)
1077
&gt;&gt;&gt; ord('e') # latin 'e', as used in English and typed using standard keyboard
101
&gt;&gt;&gt; 'е' == 'e'
False

&gt;&gt;&gt; value = 42 # latin e
&gt;&gt;&gt; valuе = 23 # cyrillic 'e', Python 2.x interpreter would raise a `SyntaxError` here
&gt;&gt;&gt; value
42
</code></pre>

<p>The built-in <code>ord()</code> function returns a character's Unicode <a href="https://en.wikipedia.org/wiki/Code_point">code point</a>, and different code positions of Cyrillic 'e' and Latin 'e' justify the behavior of the above example.</p>

<hr />

<h3>▶ Teleportation *</h3>

<pre><code>import numpy as np

def energy_send(x):
    # Initializing a numpy array
    np.array([float(x)])

def energy_receive():
    # Return an empty numpy array
    return np.empty((), dtype=np.float).tolist()
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; energy_send(123.456)
&gt;&gt;&gt; energy_receive()
123.456
</code></pre>

<p>Where's the Nobel Prize?</p>

<h4>💡 Explanation:</h4>

<ul>
<li>Notice that the numpy array created in the <code>energy_send</code> function is not returned, so that memory space is free to reallocate.</li>
<li><code>numpy.empty()</code> returns the next free memory slot without reinitializing it. This memory spot just happens to be the same one that was just freed (usually, but not always).</li>
</ul>

<hr />

<h3>▶ Well, something is fishy...</h3>

<pre><code>def square(x):
    """
    A simple function to calculate the square of a number by addition.
    """
    sum_so_far = 0
    for counter in range(x):
        sum_so_far = sum_so_far + x
  return sum_so_far
</code></pre>

<p><strong>Output (Python 2.x):</strong></p>

<pre><code>&gt;&gt;&gt; square(10)
10
</code></pre>

<p>Shouldn't that be 100?</p>

<p><strong>Note:</strong> If you're not able to reproduce this, try running the file <a href="/mixed_tabs_and_spaces.py">mixed_tabs_and_spaces.py</a> via the shell.</p>

<h4>💡 Explanation</h4>

<ul>
<li><strong>Don't mix tabs and spaces!</strong> The character just preceding return is a "tab",  and the code is indented by multiple of "4 spaces" elsewhere in the example.</li>
<li>This is how Python handles tabs:
&gt; First, tabs are replaced (from left to right) by one to eight spaces such that the total number of characters up to and including the replacement is a multiple of eight &lt;...&gt;</li>
<li>So the "tab" at the last line of <code>square</code> function is replaced with eight spaces, and it gets into the loop.</li>
<li><p>Python 3 is kind enough to throw an error for such cases automatically.</p>

<p><strong>Output (Python 3.x):</strong></p>

<pre><code>TabError: inconsistent use of tabs and spaces in indentation
</code></pre></li>
</ul>

<hr />

<hr />

<h2>Section: Watch out for the landmines!</h2>

<h3>▶ Modifying a dictionary while iterating over it</h3>

<pre><code>x = {0: None}

for i in x:
    del x[i]
    x[i+1] = None
    print(i)
</code></pre>

<p><strong>Output (Python 2.7- Python 3.5):</strong></p>

<p><code>
0
1
2
3
4
5
6
7
</code></p>

<p>Yes, it runs for exactly <strong>eight</strong> times and stops.</p>

<h4>💡 Explanation:</h4>

<ul>
<li>Iteration over a dictionary that you edit at the same time is not supported.</li>
<li>It runs eight times because that's the point at which the dictionary resizes to hold more keys (we have eight deletion entries, so a resize is needed). This is actually an implementation detail.</li>
<li>How deleted keys are handled and when the resize occurs might be different for different Python implementations.</li>
<li>For more information, you may refer to this StackOverflow <a href="https://stackoverflow.com/questions/44763802/bug-in-python-dict">thread</a> explaining a similar example in detail.</li>
</ul>

<hr />

<h3>▶ Stubborn <code>del</code> operator *</h3>

<pre><code>class SomeClass:
    def __del__(self):
        print("Deleted!")
</code></pre>

<p><strong>Output:</strong>
1.</p>

<pre><code>&gt;&gt;&gt; x = SomeClass()
&gt;&gt;&gt; y = x
&gt;&gt;&gt; del x # this should print "Deleted!"
&gt;&gt;&gt; del y
Deleted!
</code></pre>

<p>Phew, deleted at last. You might have guessed what saved from <code>__del__</code> being called in our first attempt to delete <code>x</code>. Let's add more twist to the example.</p>

<p>2.</p>

<pre><code>&gt;&gt;&gt; x = SomeClass()
&gt;&gt;&gt; y = x
&gt;&gt;&gt; del x
&gt;&gt;&gt; y # check if y exists
&lt;__main__.SomeClass instance at 0x7f98a1a67fc8&gt;
&gt;&gt;&gt; del y # Like previously, this should print "Deleted!"
&gt;&gt;&gt; globals() # oh, it didn't. Let's check all our global variables and confirm
Deleted!
{'__builtins__': &lt;module '__builtin__' (built-in)&gt;, 'SomeClass': &lt;class __main__.SomeClass at 0x7f98a1a5f668&gt;, '__package__': None, '__name__': '__main__', '__doc__': None}
</code></pre>

<p>Okay, now it's deleted :confused:</p>

<h4>💡 Explanation:</h4>

<ul>
<li><code>del x</code> doesn’t directly call <code>x.__del__()</code>.</li>
<li>Whenever <code>del x</code> is encountered, Python decrements the reference count for <code>x</code> by one, and <code>x.__del__()</code> when x’s reference count reaches zero.</li>
<li>In the second output snippet, <code>y.__del__()</code> was not called because the previous statement (<code>&gt;&gt;&gt; y</code>) in the interactive interpreter created another reference to the same object, thus preventing the reference count to reach zero when <code>del y</code> was encountered.</li>
<li>Calling <code>globals</code> caused the existing reference to be destroyed and hence we can see "Deleted!" being printed (finally!).</li>
</ul>

<hr />

<h3>▶ Deleting a list item while iterating</h3>

<pre><code>list_1 = [1, 2, 3, 4]
list_2 = [1, 2, 3, 4]
list_3 = [1, 2, 3, 4]
list_4 = [1, 2, 3, 4]

for idx, item in enumerate(list_1):
    del item

for idx, item in enumerate(list_2):
    list_2.remove(item)

for idx, item in enumerate(list_3[:]):
    list_3.remove(item)

for idx, item in enumerate(list_4):
    list_4.pop(idx)
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; list_1
[1, 2, 3, 4]
&gt;&gt;&gt; list_2
[2, 4]
&gt;&gt;&gt; list_3
[]
&gt;&gt;&gt; list_4
[2, 4]
</code></pre>

<p>Can you guess why the output is <code>[2, 4]</code>?</p>

<h4>💡 Explanation:</h4>

<ul>
<li><p>It's never a good idea to change the object you're iterating over. The correct way to do so is to iterate over a copy of the object instead, and <code>list_3[:]</code> does just that.</p>

<pre><code> &gt;&gt;&gt; some_list = [1, 2, 3, 4]
 &gt;&gt;&gt; id(some_list)
 139798789457608
 &gt;&gt;&gt; id(some_list[:]) # Notice that python creates new object for sliced list.
 139798779601192
</code></pre></li>
</ul>

<p><strong>Difference between <code>del</code>, <code>remove</code>, and <code>pop</code>:</strong>
* <code>del var_name</code> just removes the binding of the <code>var_name</code> from the local or global namespace (That's why the <code>list_1</code> is unaffected).
* <code>remove</code> removes the first matching value, not a specific index, raises <code>ValueError</code> if the value is not found.
* <code>pop</code> removes the element at a specific index and returns it, raises <code>IndexError</code> if an invalid index is specified.</p>

<p><strong>Why the output is <code>[2, 4]</code>?</strong>
- The list iteration is done index by index, and when we remove <code>1</code> from <code>list_2</code> or <code>list_4</code>, the contents of the lists are now <code>[2, 3, 4]</code>. The remaining elements are shifted down, i.e., <code>2</code> is at index 0, and <code>3</code> is at index 1. Since the next iteration is going to look at index 1 (which is the <code>3</code>), the <code>2</code> gets skipped entirely. A similar thing will happen with every alternate element in the list sequence.</p>

<ul>
<li>Refer to this StackOverflow <a href="https://stackoverflow.com/questions/45946228/what-happens-when-you-try-to-delete-a-list-element-while-iterating-over-it">thread</a> explaining the example</li>
<li>See also this nice StackOverflow <a href="https://stackoverflow.com/questions/45877614/how-to-change-all-the-dictionary-keys-in-a-for-loop-with-d-items">thread</a> for a similar example related to dictionaries in Python.</li>
</ul>

<hr />

<h3>▶ Loop variables leaking out!</h3>

<p>1.</p>

<pre><code>for x in range(7):
    if x == 6:
        print(x, ': for x inside loop')
print(x, ': x in global')
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>6 : for x inside loop
6 : x in global
</code></pre>

<p>But <code>x</code> was never defined outside the scope of for loop...</p>

<p>2.</p>

<pre><code># This time let's initialize x first
x = -1
for x in range(7):
    if x == 6:
        print(x, ': for x inside loop')
print(x, ': x in global')
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>6 : for x inside loop
6 : x in global
</code></pre>

<p>3.
<code>
x = 1
print([x for x in range(5)])
print(x, ': x in global')
</code></p>

<p><strong>Output (on Python 2.x):</strong>
<code>
[0, 1, 2, 3, 4]
(4, ': x in global')
</code></p>

<p><strong>Output (on Python 3.x):</strong>
<code>
[0, 1, 2, 3, 4]
1 : x in global
</code></p>

<h4>💡 Explanation:</h4>

<ul>
<li><p>In Python, for-loops use the scope they exist in and leave their defined loop-variable behind. This also applies if we explicitly defined the for-loop variable in the global namespace before. In this case, it will rebind the existing variable.</p></li>
<li><p>The differences in the output of Python 2.x and Python 3.x interpreters for list comprehension example can be explained by following change documented in <a href="https://docs.python.org/3/whatsnew/3.0.html">What’s New In Python 3.0</a> documentation:</p>

<blockquote>
  <p>"List comprehensions no longer support the syntactic form <code>[... for var in item1, item2, ...]</code>. Use <code>[... for var in (item1, item2, ...)]</code> instead. Also, note that list comprehensions have different semantics: they are closer to syntactic sugar for a generator expression inside a <code>list()</code> constructor, and in particular the loop control variables are no longer leaked into the surrounding scope."</p>
</blockquote></li>
</ul>

<hr />

<h3>▶ Beware of default mutable arguments!</h3>

<pre><code>def some_func(default_arg=[]):
    default_arg.append("some_string")
    return default_arg
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; some_func()
['some_string']
&gt;&gt;&gt; some_func()
['some_string', 'some_string']
&gt;&gt;&gt; some_func([])
['some_string']
&gt;&gt;&gt; some_func()
['some_string', 'some_string', 'some_string']
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li><p>The default mutable arguments of functions in Python aren't really initialized every time you call the function. Instead, the recently assigned value to them is used as the default value. When we explicitly passed <code>[]</code> to <code>some_func</code> as the argument, the default value of the <code>default_arg</code> variable was not used, so the function returned as expected.</p>

<pre><code>def some_func(default_arg=[]):
    default_arg.append("some_string")
    return default_arg
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; some_func.__defaults__ #This will show the default argument values for the function
([],)
&gt;&gt;&gt; some_func()
&gt;&gt;&gt; some_func.__defaults__
(['some_string'],)
&gt;&gt;&gt; some_func()
&gt;&gt;&gt; some_func.__defaults__
(['some_string', 'some_string'],)
&gt;&gt;&gt; some_func([])
&gt;&gt;&gt; some_func.__defaults__
(['some_string', 'some_string'],)
</code></pre></li>
<li><p>A common practice to avoid bugs due to mutable arguments is to assign <code>None</code> as the default value and later check if any value is passed to the function corresponding to that argument. Example:</p>

<pre><code>def some_func(default_arg=None):
    if not default_arg:
        default_arg = []
    default_arg.append("some_string")
    return default_arg
</code></pre></li>
</ul>

<hr />

<h3>▶ Catching the Exceptions</h3>

<pre><code>some_list = [1, 2, 3]
try:
    # This should raise an ``IndexError``
    print(some_list[4])
except IndexError, ValueError:
    print("Caught!")

try:
    # This should raise a ``ValueError``
    some_list.remove(4)
except IndexError, ValueError:
    print("Caught again!")
</code></pre>

<p><strong>Output (Python 2.x):</strong></p>

<pre><code>Caught!

ValueError: list.remove(x): x not in list
</code></pre>

<p><strong>Output (Python 3.x):</strong></p>

<pre><code>  File "&lt;input&gt;", line 3
    except IndexError, ValueError:
                     ^
SyntaxError: invalid syntax
</code></pre>

<h4>💡 Explanation</h4>

<ul>
<li><p>To add multiple Exceptions to the except clause, you need to pass them as parenthesized tuple as the first argument. The second argument is an optional name, which when supplied will bind the Exception instance that has been raised. Example,</p>

<p>some_list = [1, 2, 3]
  try:
     # This should raise a <code>ValueError</code>
     some_list.remove(4)
  except (IndexError, ValueError), e:
     print("Caught again!")
     print(e)</p>

<p><strong>Output (Python 2.x):</strong>
<code>
Caught again!
list.remove(x): x not in list
</code>
<strong>Output (Python 3.x):</strong></p>

<pre><code>File "&lt;input&gt;", line 4
  except (IndexError, ValueError), e:
                                   ^
</code></pre>

<p>IndentationError: unindent does not match any outer indentation level</p></li>
<li><p>Separating the exception from the variable with a comma is deprecated and does not work in Python 3; the correct way is to use <code>as</code>. Example,</p>

<p>some_list = [1, 2, 3]
  try:
      some_list.remove(4)</p>

<p>except (IndexError, ValueError) as e:
      print("Caught again!")
      print(e)</p>

<p><strong>Output:</strong>
<code>
Caught again!
list.remove(x): x not in list
</code></p></li>
</ul>

<hr />

<h3>▶ Same operands, different story!</h3>

<p>1.</p>

<pre><code>a = [1, 2, 3, 4]
b = a
a = a + [5, 6, 7, 8]
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; a
[1, 2, 3, 4, 5, 6, 7, 8]
&gt;&gt;&gt; b
[1, 2, 3, 4]
</code></pre>

<p>2.</p>

<pre><code>a = [1, 2, 3, 4]
b = a
a += [5, 6, 7, 8]
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; a
[1, 2, 3, 4, 5, 6, 7, 8]
&gt;&gt;&gt; b
[1, 2, 3, 4, 5, 6, 7, 8]
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li><p><code>a += b</code> doesn't always behave the same way as <code>a = a + b</code>.  Classes <em>may</em> implement the <em><code>op=</code></em> operators differently, and lists do this.</p></li>
<li><p>The expression <code>a = a + [5,6,7,8]</code> generates a new list and sets <code>a</code>'s reference to that new list, leaving <code>b</code> unchanged.</p></li>
<li><p>The expression <code>a += [5,6,7,8]</code> is actually mapped to an "extend" function that operates on the list such that <code>a</code> and <code>b</code> still point to the same list that has been modified in-place.</p></li>
</ul>

<hr />

<h3>▶ The out of scope variable</h3>

<pre><code>a = 1
def some_func():
    return a

def another_func():
    a += 1
    return a
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; some_func()
1
&gt;&gt;&gt; another_func()
UnboundLocalError: local variable 'a' referenced before assignment
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>When you make an assignment to a variable in scope, it becomes local to that scope. So <code>a</code> becomes local to the scope of <code>another_func</code>,  but it has not been initialized previously in the same scope which throws an error.</li>
<li>Read <a href="http://sebastianraschka.com/Articles/2014_python_scope_and_namespaces.html">this</a> short but an awesome guide to learn more about how namespaces and scope resolution works in Python.</li>
<li><p>To modify the outer scope variable <code>a</code> in <code>another_func</code>, use <code>global</code> keyword.</p>

<p>def another_func()
      global a
      a += 1
      return a</p>

<p><strong>Output:</strong></p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>another_func()
        2</p>
    </blockquote>
  </blockquote>
</blockquote></li>
</ul>

<hr />

<h3>▶ Be careful with chained operations</h3>

<pre><code>&gt;&gt;&gt; (False == False) in [False] # makes sense
False
&gt;&gt;&gt; False == (False in [False]) # makes sense
False
&gt;&gt;&gt; False == False in [False] # now what?
True

&gt;&gt;&gt; True is False == False
False
&gt;&gt;&gt; False is False is False
True

&gt;&gt;&gt; 1 &gt; 0 &lt; 1
True
&gt;&gt;&gt; (1 &gt; 0) &lt; 1
False
&gt;&gt;&gt; 1 &gt; (0 &lt; 1)
False
</code></pre>

<h4>💡 Explanation:</h4>

<p>As per https://docs.python.org/2/reference/expressions.html#not-in</p>

<blockquote>
  <p>Formally, if a, b, c, ..., y, z are expressions and op1, op2, ..., opN are comparison operators, then a op1 b op2 c ... y opN z is equivalent to a op1 b and b op2 c and ... y opN z, except that each expression is evaluated at most once.</p>
</blockquote>

<p>While such behavior might seem silly to you in the above examples, it's fantastic with stuff like <code>a == b == c</code> and <code>0 &lt;= x &lt;= 100</code>.</p>

<ul>
<li><code>False is False is False</code> is equivalent to <code>(False is False) and (False is False)</code></li>
<li><code>True is False == False</code> is equivalent to <code>True is False and False == False</code> and since the first part of the statement (<code>True is False</code>) evaluates to <code>False</code>, the overall expression evaluates to <code>False</code>.</li>
<li><code>1 &gt; 0 &lt; 1</code> is equivalent to <code>1 &gt; 0 and 0 &lt; 1</code> which evaluates to <code>True</code>.</li>
<li><p>The expression <code>(1 &gt; 0) &lt; 1</code> is equivalent to <code>True &lt; 1</code> and</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>int(True)
        1
      True + 1 #not relevant for this example, but just for fun
        2</p>
    </blockquote>
  </blockquote>
</blockquote>

<p>So, <code>1 &lt; 1</code> evaluates to <code>False</code></p></li>
</ul>

<hr />

<h3>▶ Name resolution ignoring class scope</h3>

<p>1.</p>

<pre><code>x = 5
class SomeClass:
    x = 17
    y = (x for i in range(10))
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; list(SomeClass.y)[0]
5
</code></pre>

<p>2.</p>

<pre><code>x = 5
class SomeClass:
    x = 17
    y = [x for i in range(10)]
</code></pre>

<p><strong>Output (Python 2.x):</strong></p>

<pre><code>&gt;&gt;&gt; SomeClass.y[0]
17
</code></pre>

<p><strong>Output (Python 3.x):</strong></p>

<pre><code>&gt;&gt;&gt; SomeClass.y[0]
5
</code></pre>

<h4>💡 Explanation</h4>

<ul>
<li>Scopes nested inside class definition ignore names bound at the class level.</li>
<li>A generator expression has its own scope.</li>
<li>Starting from Python 3.X, list comprehensions also have their own scope.</li>
</ul>

<hr />

<h3>▶ Needle in a Haystack</h3>

<p>1.</p>

<pre><code>x, y = (0, 1) if True else None, None
</code></pre>

<p><strong>Output:</strong>
```</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>x, y  # expected (0, 1)
      ((0, 1), None)
      ```</p>
    </blockquote>
  </blockquote>
</blockquote>

<p>Almost every Python programmer has faced a similar situation.</p>

<p>2.</p>

<pre><code>t = ('one', 'two')
for i in t:
    print(i)

t = ('one')
for i in t:
    print(i)

t = ()
print(t)
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>one
two
o
n
e
tuple()
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>For 1, the correct statement for expected behavior is <code>x, y = (0, 1) if True else (None, None)</code>.</li>
<li>For 2, the correct statement for expected behavior is <code>t = ('one',)</code> or <code>t = 'one',</code> (missing comma) otherwise the interpreter considers <code>t</code> to be a <code>str</code> and iterates over it character by character.</li>
<li><code>()</code> is a special token and denotes empty <code>tuple</code>.</li>
</ul>

<hr />

<hr />

<h2>Section: The Hidden treasures!</h2>

<p>This section contains few of the lesser-known interesting things about Python that most beginners like me are unaware of (well, not anymore).</p>

<h3>▶ Okay Python, Can you make me fly? *</h3>

<p>Well, here you go</p>

<pre><code>import antigravity
</code></pre>

<p><strong>Output:</strong>
Sshh.. It's a super secret.</p>

<h4>💡 Explanation:</h4>

<ul>
<li><code>antigravity</code> module is one of the few easter eggs released by Python developers.</li>
<li><code>import antigravity</code> opens up a web browser pointing to the <a href="http://xkcd.com/353/">classic XKCD comic</a> about Python.</li>
<li>Well, there's more to it. There's <strong>another easter egg inside the easter egg</strong>. If look at the <a href="https://github.com/python/cpython/blob/master/Lib/antigravity.py#L7-L17">code</a>, there's a function defined that purports to implement the <a href="https://xkcd.com/426/">XKCD's geohashing algorithm</a>.</li>
</ul>

<hr />

<h3>▶ <code>goto</code>, but why? *</h3>

<pre><code>from goto import goto, label
for i in range(9):
    for j in range(9):
        for k in range(9):
            print("I'm trapped, please rescue!")
            if k == 2:
                goto .breakout # breaking out from a deeply nested loop
label .breakout
print("Freedom!")
</code></pre>

<p><strong>Output (Python 2.3):</strong></p>

<pre><code>I'm trapped, please rescue!
I'm trapped, please rescue!
Freedom!
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>A working version of <code>goto</code> in Python was <a href="https://mail.python.org/pipermail/python-announce-list/2004-April/002982.html">announced</a> as an April Fool's joke on 1st April 2004.</li>
<li>Current versions of Python do not have this module.</li>
<li>Although it works, but please don't use it. Here's the <a href="https://docs.python.org/3/faq/design.html#why-is-there-no-goto">reason</a> to why <code>goto</code> is not present in Python.</li>
</ul>

<hr />

<h3>▶ Brace yourself! *</h3>

<p>If you are one of the people who doesn't like using whitespace in Python to denote scopes, you can use the C-style {} by importing,</p>

<pre><code>from __future__ import braces
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>  File "some_file.py", line 1
    from __future__ import braces
SyntaxError: not a chance
</code></pre>

<p>Braces? No way! If you think that's disappointing, use Java.</p>

<h4>💡 Explanation:</h4>

<ul>
<li>The <code>__future__</code> module is normally used to provide features from future versions of Python. The "future" here is however ironic.</li>
<li>This is an easter egg concerned with the community's feelings on this issue.</li>
</ul>

<hr />

<h3>▶ Let's meet Friendly Language Uncle For Life *</h3>

<p><strong>Output (Python 3.x)</strong></p>

<pre><code>&gt;&gt;&gt; from __future__ import barry_as_FLUFL
&gt;&gt;&gt; "Ruby" != "Python" # there's no doubt about it
  File "some_file.py", line 1
    "Ruby" != "Python"
              ^
SyntaxError: invalid syntax

&gt;&gt;&gt; "Ruby" &lt;&gt; "Python"
True
</code></pre>

<p>There we go.</p>

<h4>💡 Explanation:</h4>

<ul>
<li>This is relevant to <a href="https://www.python.org/dev/peps/pep-0401/">PEP-401</a> released on April 1, 2009 (now you know, what it means).</li>
<li>Quoting from the PEP-401
&gt; Recognized that the != inequality operator in Python 3.0 was a horrible, finger pain inducing mistake, the FLUFL reinstates the &lt;&gt; diamond operator as the sole spelling.</li>
<li>There were more things that Uncle Barry had to share in the PEP; you can read them <a href="https://www.python.org/dev/peps/pep-0401/">here</a>.</li>
</ul>

<hr />

<h3>▶ Even Python understands that love is complicated *</h3>

<pre><code>import this
</code></pre>

<p>Wait, what's <strong>this</strong>? <code>this</code> is love :heart:</p>

<p><strong>Output:</strong>
```
The Zen of Python, by Tim Peters</p>

<p>Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than <em>right</em> now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
```</p>

<p>It's the Zen of Python!</p>

<pre><code>&gt;&gt;&gt; love = this
&gt;&gt;&gt; this is love
True
&gt;&gt;&gt; love is True
False
&gt;&gt;&gt; love is False
False
&gt;&gt;&gt; love is not True or False
True
&gt;&gt;&gt; love is not True or False; love is love  # Love is complicated
True
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li><code>this</code> module in Python is an easter egg for The Zen Of Python (<a href="https://www.python.org/dev/peps/pep-0020">PEP 20</a>).</li>
<li>And if you think that's already interesting enough, check out the implementation of <a href="https://hg.python.org/cpython/file/c3896275c0f6/Lib/this.py">this.py</a>. Interestingly, the code for the Zen violates itself (and that's probably the only place where this happens).</li>
<li>Regarding the statement <code>love is not True or False; love is love</code>, ironic but it's self-explanatory.</li>
</ul>

<hr />

<h3>▶ Yes, it exists!</h3>

<p><strong>The <code>else</code> clause for loops.</strong> One typical example might be:</p>

<pre><code>  def does_exists_num(l, to_find):
      for num in l:
          if num == to_find:
              print("Exists!")
              break
      else:
          print("Does not exist")
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; some_list = [1, 2, 3, 4, 5]
&gt;&gt;&gt; does_exists_num(some_list, 4)
Exists!
&gt;&gt;&gt; does_exists_num(some_list, -1)
Does not exist
</code></pre>

<p><strong>The <code>else</code> clause in exception handling.</strong> An example,</p>

<pre><code>try:
    pass
except:
    print("Exception occurred!!!")
else:
    print("Try block executed successfully...")
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>Try block executed successfully...
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>The <code>else</code> clause after a loop is executed only when there's no explicit <code>break</code> after all the iterations.</li>
<li><code>else</code> clause after try block is also called "completion clause" as reaching the <code>else</code> clause in a <code>try</code> statement means that the try block actually completed successfully.</li>
</ul>

<hr />

<h3>▶ Inpinity *</h3>

<p>The spelling is intended. Please, don't submit a patch for this.</p>

<p><strong>Output (Python 3.x):</strong></p>

<pre><code>&gt;&gt;&gt; infinity = float('infinity')
&gt;&gt;&gt; hash(infinity)
314159
&gt;&gt;&gt; hash(float('-inf'))
-314159
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li>Hash of infinity is 10⁵ x π.</li>
<li>Interestingly, the hash of <code>float('-inf')</code> is "-10⁵ x π" in Python 3, whereas "-10⁵ x e" in Python 2.</li>
</ul>

<hr />

<h3>▶ Mangling time! *</h3>

<pre><code>class Yo(object):
    def __init__(self):
        self.__honey = True
        self.bitch = True
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; Yo().bitch
True
&gt;&gt;&gt; Yo().__honey
AttributeError: 'Yo' object has no attribute '__honey'
&gt;&gt;&gt; Yo()._Yo__honey
True
</code></pre>

<p>Why did <code>Yo()._Yo__honey</code> work? Only Indian readers would understand.</p>

<h4>💡 Explanation:</h4>

<ul>
<li><a href="https://en.wikipedia.org/wiki/Name_mangling">Name Mangling</a> is used to avoid naming collisions between different namespaces.</li>
<li>In Python, the interpreter modifies (mangles) the class member names starting with <code>__</code> (double underscore) and not ending with more than one trailing underscore by adding <code>_NameOfTheClass</code> in front.</li>
<li>So, to access <code>__honey</code> attribute, we are required to append <code>_Yo</code> to the front which would prevent conflicts with the same name attribute defined in any other class.</li>
</ul>

<hr />

<hr />

<h2>Section: Miscellaneous</h2>

<h3>▶ <code>+=</code> is faster</h3>

<pre><code># using "+", three strings:
&gt;&gt;&gt; timeit.timeit("s1 = s1 + s2 + s3", setup="s1 = ' ' * 100000; s2 = ' ' * 100000; s3 = ' ' * 100000", number=100)
0.25748300552368164
# using "+=", three strings:
&gt;&gt;&gt; timeit.timeit("s1 += s2 + s3", setup="s1 = ' ' * 100000; s2 = ' ' * 100000; s3 = ' ' * 100000", number=100)
0.012188911437988281
</code></pre>

<h4>💡 Explanation:</h4>

<ul>
<li><code>+=</code> is faster than <code>+</code> for concatenating more than two strings because the first string (example, <code>s1</code> for <code>s1 += s2 + s3</code>) is not destroyed while calculating the complete string.</li>
</ul>

<hr />

<h3>▶ Let's make a giant string!</h3>

<pre><code>def add_string_with_plus(iters):
    s = ""
    for i in range(iters):
        s += "xyz"
    assert len(s) == 3*iters

def add_bytes_with_plus(iters):
    s = b""
    for i in range(iters):
        s += b"xyz"
    assert len(s) == 3*iters

def add_string_with_format(iters):
    fs = "{}"*iters
    s = fs.format(*(["xyz"]*iters))
    assert len(s) == 3*iters

def add_string_with_join(iters):
    l = []
    for i in range(iters):
        l.append("xyz")
    s = "".join(l)
    assert len(s) == 3*iters

def convert_list_to_string(l, iters):
    s = "".join(l)
    assert len(s) == 3*iters
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; timeit(add_string_with_plus(10000))
1000 loops, best of 3: 972 µs per loop
&gt;&gt;&gt; timeit(add_bytes_with_plus(10000))
1000 loops, best of 3: 815 µs per loop
&gt;&gt;&gt; timeit(add_string_with_format(10000))
1000 loops, best of 3: 508 µs per loop
&gt;&gt;&gt; timeit(add_string_with_join(10000))
1000 loops, best of 3: 878 µs per loop
&gt;&gt;&gt; l = ["xyz"]*10000
&gt;&gt;&gt; timeit(convert_list_to_string(l, 10000))
10000 loops, best of 3: 80 µs per loop
</code></pre>

<p>Let's increase the number of iterations by a factor of 10.</p>

<pre><code>&gt;&gt;&gt; timeit(add_string_with_plus(100000)) # Linear increase in execution time
100 loops, best of 3: 9.75 ms per loop
&gt;&gt;&gt; timeit(add_bytes_with_plus(100000)) # Quadratic increase
1000 loops, best of 3: 974 ms per loop
&gt;&gt;&gt; timeit(add_string_with_format(100000)) # Linear increase
100 loops, best of 3: 5.25 ms per loop
&gt;&gt;&gt; timeit(add_string_with_join(100000)) # Linear increase
100 loops, best of 3: 9.85 ms per loop
&gt;&gt;&gt; l = ["xyz"]*100000
&gt;&gt;&gt; timeit(convert_list_to_string(l, 100000)) # Linear increase
1000 loops, best of 3: 723 µs per loop
</code></pre>

<h4>💡 Explanation</h4>

<ul>
<li>You can read more about <a href="https://docs.python.org/3/library/timeit.html">timeit</a> from here. It is generally used to measure the execution time of snippets.</li>
<li>Don't use <code>+</code> for generating long strings — In Python, <code>str</code> is immutable, so the left and right strings have to be copied into the new string for every pair of concatenations. If you concatenate four strings of length 10, you'll be copying (10+10) + ((10+10)+10) + (((10+10)+10)+10) = 90 characters instead of just 40 characters. Things get quadratically worse as the number and size of the string increases (justified with the execution times of <code>add_bytes_with_plus</code> function)</li>
<li>Therefore, it's advised to use <code>.format.</code> or <code>%</code> syntax (however, they are slightly slower than <code>+</code> for short strings).</li>
<li>Or better, if already you've contents available in the form of an iterable object, then use <code>''.join(iterable_object)</code> which is much faster.</li>
<li><p><code>add_string_with_plus</code> didn't show a quadratic increase in execution time unlike <code>add_bytes_with_plus</code> because of the <code>+=</code> optimizations discussed in the previous example. Had the statement been <code>s = s + "x" + "y" + "z"</code> instead of <code>s += "xyz"</code>, the increase would have been quadratic.</p>

<p>def add_string_with_plus(iters):
      s = ""
      for i in range(iters):
          s = s + "x" + "y" + "z"
      assert len(s) == 3*iters</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>timeit(add_string_with_plus(10000))
        100 loops, best of 3: 9.87 ms per loop
      timeit(add_string_with_plus(100000)) # Quadratic increase in execution time
        1 loops, best of 3: 1.09 s per loop</p>
    </blockquote>
  </blockquote>
</blockquote></li>
</ul>

<hr />

<h3>▶ Explicit typecast of strings</h3>

<pre><code>a = float('inf')
b = float('nan')
c = float('-iNf')  #These strings are case-insensitive
d = float('nan')
</code></pre>

<p><strong>Output:</strong></p>

<pre><code>&gt;&gt;&gt; a
inf
&gt;&gt;&gt; b
nan
&gt;&gt;&gt; c
-inf
&gt;&gt;&gt; float('some_other_string')
ValueError: could not convert string to float: some_other_string
&gt;&gt;&gt; a == -c #inf==inf
True
&gt;&gt;&gt; None == None # None==None
True
&gt;&gt;&gt; b == d #but nan!=nan
False
&gt;&gt;&gt; 50/a
0.0
&gt;&gt;&gt; a/a
nan
&gt;&gt;&gt; 23 + b
nan
</code></pre>

<h4>💡 Explanation:</h4>

<p><code>'inf'</code> and <code>'nan'</code> are special strings (case-insensitive), which when explicitly typecasted to <code>float</code> type, are used to represent mathematical "infinity" and "not a number" respectively.</p>

<hr />

<h3>▶ Minor Ones</h3>

<ul>
<li><p><code>join()</code> is a string operation instead of list operation. (sort of counter-intuitive at first usage)</p>

<p><strong>💡 Explanation:</strong>
If <code>join()</code> is a method on a string then it can operate on any iterable (list, tuple, iterators). If it were a method on a list, it'd have to be implemented separately by every type. Also, it doesn't make much sense to put a string-specific method on a generic <code>list</code> object API.</p></li>
<li><p>Few weird looking but semantically correct statements:</p>

<ul>
<li><code>[] = ()</code> is a semantically correct statement (unpacking an empty <code>tuple</code> into an empty <code>list</code>)</li>
<li><code>'a'[0][0][0][0][0]</code> is also a semantically correct statement as strings are <a href="https://docs.python.org/3/glossary.html#term-sequence">sequences</a>(iterables supporting element access using integer indices) in Python.</li>
<li><code>3 --0-- 5 == 8</code> and <code>--5 == 5</code> are both semantically correct statements and evaluate to <code>True</code>.</li>
</ul></li>
<li><p>Given that <code>a</code> is a number, <code>++a</code> and <code>--a</code> are both valid Python statements but don't behave the same way as compared with similar statements in languages like C, C++ or Java.</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>a = 5
      a
        5
      ++a
        5
      --a
        5</p>
    </blockquote>
  </blockquote>
</blockquote>

<p><strong>💡 Explanation:</strong></p>

<ul>
<li>There is no <code>++</code> operator in Python grammar. It is actually two <code>+</code> operators.</li>
<li><code>++a</code> parses as <code>+(+a)</code> which translates to <code>a</code>. Similarly, the output of the statement <code>--a</code> can be justified.</li>
<li>This StackOverflow <a href="https://stackoverflow.com/questions/3654830/why-are-there-no-and-operators-in-python">thread</a> discusses the rationale behind the absence of increment and decrement operators in Python.</li>
</ul></li>
<li><p>Python uses 2 bytes for local variable storage in functions. In theory, this means that only 65536 variables can be defined in a function. However, python has a handy solution built in that can be used to store more than 2^16 variable names. The following code demonstrates what happens in the stack when more than 65536 local variables are defined (Warning: This code prints around 2^18 lines of text, so be prepared!):</p>

<pre><code> import dis
 exec("""
 def f():
     """ + """
     """.join(["X"+str(x)+"=" + str(x) for x in range(65539)]))

 f()

 print(dis.dis(f))
</code></pre></li>
<li><p>Multiple Python threads won't run your <em>Python code</em> concurrently (yes you heard it right!). It may seem intuitive to spawn several threads and let them execute your Python code concurrently, but, because of the <a href="https://wiki.python.org/moin/GlobalInterpreterLock">Global Interpreter Lock</a> in Python, all you're doing is making your threads execute on the same core turn by turn. Python threads are good for IO-bound tasks, but to achieve actual parallelization in Python for CPU-bound tasks, you might want to use the Python <a href="https://docs.python.org/2/library/multiprocessing.html">multiprocessing</a> module.</p></li>
<li><p>List slicing with out of the bounds indices throws no errors</p>

<blockquote>
  <blockquote>
    <blockquote>
      <p>some_list = [1, 2, 3, 4, 5]
      some_list[111:]
        []</p>
    </blockquote>
  </blockquote>
</blockquote></li>
<li><p><code>int('١٢٣٤٥٦٧٨٩')</code> returns <code>123456789</code> in Python 3. In Python, Decimal characters include digit characters, and all characters that can be used to form decimal-radix numbers, e.g. U+0660, ARABIC-INDIC DIGIT ZERO. Here's an <a href="http://chris.improbable.org/2014/8/25/adventures-in-unicode-digits/">interesting story</a> related to this behavior of Python.</p></li>
<li><p><code>'abc'.count('') == 4</code>. Here's an approximate implementation of <code>count</code> method, which would make the things more clear</p>

<p>def count(s, sub):
      result = 0
      for i in range(len(s) + 1 - len(sub)):
          result += (s[i:i + len(sub)] == sub)
      return result</p>

<p>The behavior is due to the matching of empty substring(<code>''</code>) with slices of length 0 in the original string.</p></li>
</ul>

<hr />

<h1>Contributing</h1>

<p>All patches are Welcome! Please see <a href="/CONTRIBUTING.md">CONTRIBUTING.md</a> for further details.</p>

<p>For discussions, you can either create a new <a href="https://github.com/satwikkansal/wtfpython/issues/new">issue</a> or ping on the Gitter <a href="https://gitter.im/wtfpython/Lobby">channel</a></p>

<h1>Acknowledgements</h1>

<p>The idea and design for this collection were initially inspired by Denys Dovhan's awesome project <a href="https://github.com/denysdovhan/wtfjs">wtfjs</a>. The overwhelming support by the community gave it the shape it is in right now.</p>

<h4>Some nice Links!</h4>

<ul>
<li>https://www.youtube.com/watch?v=sH4XF6pKKmk</li>
<li>https://www.reddit.com/r/Python/comments/3cu6ej/what_are_some_wtf_things_about_python</li>
<li>https://sopython.com/wiki/Common_Gotchas_In_Python</li>
<li>https://stackoverflow.com/questions/530530/python-2-x-gotchas-and-landmines</li>
<li>https://stackoverflow.com/questions/1011431/common-pitfalls-in-python</li>
<li>https://www.python.org/doc/humor/</li>
<li>https://www.satwikkansal.xyz/archives/posts/python/My-Python-archives/</li>
</ul>

<h1>🎓 License</h1>

<p><a href="http://www.wtfpl.net"><img src="https://img.shields.io/badge/License-WTFPL%202.0-lightgrey.svg?style=flat-square" alt="CC 4.0" /></a></p>

<p>&copy; <a href="https://satwikkansal.xyz">Satwik Kansal</a></p>

<h2>Help</h2>

<p>If you have any wtfs, ideas or suggestions, please share.</p>

<h2>Want to surprise your geeky pythonist friends?</h2>

<p>You can recommend wtfpython to your friends on Twitter and Linkedin by using these quick links,</p>

<p><a href="https://twitter.com/intent/tweet?url=https://github.com/satwikkansal/wtfpython&amp;hastags=python,wtfpython">Twitter</a>
 | <a href="https://www.linkedin.com/shareArticle?url=https://github.com/satwikkansal&amp;title=What%20the%20f*ck%20Python!&amp;summary=An%20interesting%20collection%20of%20subtle%20and%20tricky%20Python%20snippets.">Linkedin</a></p>

<h2>Need a pdf version?</h2>

<p>I've received a few requests for the pdf version of wtfpython. You can add your details <a href="https://satwikkansal.xyz/wtfpython-pdf/">here</a> to get the pdf as soon as it is finished.</p>
